development: &development
  adapter: postgresql
  encoding: utf8
  database: imdb_api_development
  pool: 5
  username: 
  password:

test:
  <<: *development
  database: imdb_api_test

production:
  <<: *development
  database: imdb_api_production
